version: '3'
services:
  nginx:
    container_name: nginx
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - "../app:/app"
#      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
#      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/logs"
  mysql:
    container_name: mysql
    image: mysql:5
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      MAILCATCHER_PORT: 1025
