FROM northstack:latest

RUN apk add \
        curl \
        jq \
        rsync \
        docker \
        bash \
        py-pip \
        mysql-client \
    && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
        && chmod +x wp-cli.phar \
        && mv wp-cli.phar /usr/local/bin/wp \
    && pip install docker-compose \
    && docker-php-ext-install \
        mysqli \
        pdo_mysql
