FROM northstack:latest

RUN apk add \
        curl \
        jq \
        rsync \
        docker \
        bash

ARG NORTHSTACK_USER
ARG NORTHSTACK_UID
ARG NORTHSTACK_GROUP
ARG NORTHSTACK_GID
ARG DOCKER_GROUP
ARG DOCKER_GID

COPY entrypoint-test.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
