---
version: '3.4'

services:

  web:
    image: jekyll/jekyll:3
    command: "jekyll serve"
    ports:
      - 4000:4000
    volumes:
      - "${APP_APP}:/srv/jekyll"
    labels:
      com.northstack: 1
      com.northstack.localdev: 1
      com.northstack.localdev.role: web
      com.northstack.app.id: "${APP_ID}"
    environment:
      - PRIMARY_DOMAIN
      - STACK
      - EXPOSE_HTTP_PORT
