---
version: '3'

networks:
  northstack_local_dev:

services:
  web:
    image: web
    build:
      context: ./images/web
    ports:
      - '${EXPOSE_WEB_HTTP}:80'
      - '${EXPOSE_WEB_HTTPS}:443'
    volumes:
      - "${APP_PUBLIC}:/app/public"
    environment:
      - STACK
      - EXPOSE_WEB_HTTP
      - EXPOSE_WEB_HTTPS
    networks:
      northstack_local_dev: {}
