---
version: '3.4'

networks:
  northstack_local_dev:
    labels:
      com.northstack.localdev: 1

services:
  web:
    image: web
    build:
      context: ./images/web
    ports:
      - '${EXPOSE_HTTP_PORT}:80'
    volumes:
      - "${APP_PUBLIC}:/app/public"
    environment:
      - STACK
      - EXPOSE_HTTP_PORT
    networks:
      northstack_local_dev: {}
    labels:
      com.northstack.localdev: 1
    healthcheck:
      test: 'wget -qO- http://localhost/nginx_status || exit 1'
