---
version: '3.4'

networks:
  northstack_local_dev:
    labels:
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
      com.northstack: 1

services:
  web:
    image: nginx:alpine
    ports:
      - '${EXPOSE_HTTP_PORT}:80'
    volumes:
      - "${APP_PUBLIC}:/app/public"
      - '${COMPOSE_ROOT_HOST}/assets/nginx/main.conf:/etc/nginx/nginx.conf:ro'
      - '${COMPOSE_ROOT_HOST}/assets/nginx/${STACK}.nginx.conf:/etc/nginx/stack.conf:ro'
    environment:
      - STACK
      - EXPOSE_HTTP_PORT
      - PRIMARY_DOMAIN
    networks:
      northstack_local_dev: {}
    labels:
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
      com.northstack.localdev.role: web
      com.northstack: 1
    healthcheck:
      test: 'wget -qO- http://localhost/nginx_status || exit 1'
      interval: 1s
      start_period: 5s
