---
version: '3.4'

volumes:
  mysql:
    name: "${APP_ID}_mysql"
    labels:
      com.northstack.app.id: "${APP_ID}"
      com.northstack.localdev: 1
      com.northstack: 1

services:
  web:
    depends_on:
      - nginx-unit-php
    environment:
      - PRIMARY_DOMAIN
      - STACK
      - EXPOSE_HTTP_PORT

  wordpress:
    image: northstack-wordpress
    build:
      context: ./images/wordpress
      labels:
        com.northstack.localdev: 1
        com.northstack: 1
    volumes:
      - "${APP_ROOT}/app:/app"
      - "${APP_ROOT}:${APP_ROOT}"
    working_dir: "${APP_ROOT}/app/public"
    user: "${NORTHSTACK_UID}:${NORTHSTACK_GID}"
    environment:
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_PASS: ${WORDPRESS_ADMIN_PASS}
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      EXPOSE_MYSQL_PORT: ${EXPOSE_MYSQL_PORT}
      EXPOSE_HTTP_PORT: ${EXPOSE_HTTP_PORT}
    depends_on:
      - mysql
    networks:
      northstack_local_dev: {}
    labels:
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
      com.northstack.localdev.role: wordpress
      com.northstack: 1
    healthcheck:
      test: 'test -f /tmp/.finished || exit 1'
      start_period: 5s
      interval: 5s

  nginx-unit-php:
    image: northstack/nginx-unit-php:7.2-2018.12.18
    volumes:
      - "${APP_PUBLIC}:/app/public"
    depends_on:
      - wordpress
    healthcheck:
      test: 'curl -s -o /dev/null -D - --unix /var/run/control.unit.sock http://localhost/config || exit 1'
      start_period: 5s
      interval: 5s
    environment:
      - NORTHSTACK_UID
      - NORTHSTACK_GID
      - NORTHSTACK_USER
      - NORTHSTACK_GROUP
      - WORDPRESS_DB_HOST=mysql
      - EXPOSE_HTTP_PORT
    networks:
      northstack_local_dev:
        aliases:
          - nginx-unit-php
    labels:
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
      com.northstack.localdev.role: nginx-unit
      com.northstack: 1

  mysql:
    image: mysql:5
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

    ports:
      - "${EXPOSE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      northstack_local_dev:
        aliases:
          - mysql
    labels:
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
      com.northstack.localdev.role: mysql
      com.northstack: 1
    healthcheck:
      test: 'mysql -u "wordpress" -p"password" "wordpress" -e "SELECT NOW();" || exit 1'
      start_period: 5s
      interval: 5s
