---
version: '3.4'

services:

  web:
    image: jekyll/jekyll:3
    cmd: serve
    ports:
      - 4000:4000
    volumes:
      - "${APP_ROOT}/app:/srv/jekyll"
    labels:
      com.northstack: 1
      com.northstack.localdev: 1
      com.northstack.localdev.role: web
      com.northstack.app.id: "${APP_ID}"
    user: "${NORTHSTACK_UID}:${NORTHSTACK_GID}"
    environment:
      - PRIMARY_DOMAIN
      - STACK
      - EXPOSE_HTTP_PORT
      - JEKYLL_UID="${NORTHSTACK_UID}"
      - JEKYLL_GID="${NORTHSTACK_GID}"
