---
version: '3.4'

services:
  web:
    container_name: ns-gatsby-${APP_ID}
    build:
      context: ./images/gatsby
      args:
        APP_APP: "${APP_APP}"
        FRAMEWORK_VERSION: "${FRAMEWORK_VERSION}"
    ports:
      - 8000:8000
    volumes:
      - "${APP_APP}:${APP_APP}"
      - ./images/gatsby/gatsby-init:/gatsby-init
    labels:
      com.northstack: 1
      com.northstack.localdev: 1
      com.northstack.app.id: "${APP_ID}"
    environment:
      - PRIMARY_DOMAIN
      - STACK
      - EXPOSE_HTTP_PORT
      - APP_APP
      - APP_ROOT
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
