---
version: '3.4'

services:
  web:
    image: nginx
    volumes:
      - "${APP_ROOT}/app:/usr/share/nginx/html"
    depends_on:
      - builder

  builder:
    image: northstack-static-builder
    build:
      context: ./images/builder
      labels:
        com.northstack.localdev: 1
        com.northstack: 1
    volumes:
      - "${APP_ROOT}/app:/app"
    labels:
      com.northstack: 1
      com.northstack.localdev: 1
      com.northstack.localdev.role: builder
      com.northstack.app.id: "${APP_ID}"
    user: "${NORTHSTACK_UID}:${NORTHSTACK_GID}"
    environment:
      - PRIMARY_DOMAIN
      - STACK
      - EXPOSE_HTTP_PORT

